In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math as m

## 1. How likely is it that you roll doubles when rolling two dice?

In [2]:

#theoretical: 
#6x6=36 combinations 6 sets of pairs 6/36 = 1/6 = 0.166


In [128]:
doubles = np.random.choice([1, 2, 3, 4, 5, 6], size = (10_000_000, 2))
doubles

array([[6, 1],
       [6, 6],
       [3, 4],
       ...,
       [3, 5],
       [3, 3],
       [3, 3]])

In [129]:
db = pd.DataFrame(doubles)

In [130]:
db['double'] = (db[0] == db[1])

In [131]:
db.double.mean()

0.1668081

In [132]:
#it matches theoretical YAYY!

##### Second method , take some time

In [134]:
db.apply(lambda row: row[0] == row[1], axis =1).mean()

0.1668081

# Class

In [155]:
rolls = np.random.choice([1, 2, 3, 4, 5, 6], size = (10_000, 2))

In [157]:
(rolls[:,0]==rolls[:,1]).mean() #slice and compare

0.1662

In [158]:
rolls1 = np.random.choice([1, 2, 3, 4, 5, 6], size = (10_000, 1))
rolls2 = np.random.choice([1, 2, 3, 4, 5, 6], size = (10_000, 1))

In [160]:
(rolls1==rolls2).mean()

0.1677

## #2 If you flip 8 coins, what is the probability of getting exactly 3 heads? 
## What is the probability of getting more than 3 heads?


In [8]:
coin = np.random.choice(['tail', 'head'], size = (1000000, 8))
cf = pd.DataFrame(coin)

In [9]:
cft = (cf == 'head')

In [10]:
cft['total'] = cft.sum(axis =1) 

In [11]:
th = cft[cft.total == 3]
len(th)/len(cf) #probability of getting 3 heads

0.219195

In [12]:
tp = cft[cft.total > 3]
len(tp)/len(cf) #prbability of getting > 3 heads

0.636513

In [13]:
to = cft[cft.total >= 3]
len(to)/len(cf) #probability of getting >= 3

0.855708

# Class

In [164]:
flips = np.random.choice([0, 1], size = (1_000_000, 8))


In [166]:
(flips.sum(axis=1)==3).mean()

0.219574

In [167]:
(flips.sum(axis=1)>3).mean()

0.635693

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [175]:
#theory #odds = p/(1-p) p=bb.sum(axis =1).mean()
.25*.25

0.0625

In [14]:
bb = np.random.choice(['wb1', 'wd2', 'wd3', 'ds1'], size = (1000000,2))
b = pd.DataFrame(bb)

In [15]:
b['match']=(b[0]==b[1])

In [168]:
b['match'].mean() #mean is 0.24933 but that includes all the doubles, not just DS doubles

0.250039

In [17]:
len(b[(b[0] == 'ds1') & (b['match']==True)])/len(b) #6% chance it will be 2 DS students

0.062576

# Class

In [171]:
bb2 = np.random.choice([0, 1], size = (10_000, 2), p = [.75, .25])

In [173]:
(bb2.sum(axis =1) == 2).mean()

0.0624

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [3]:
l= np.random.normal(loc = 3, scale = 1.5, size = (10_000, 5))

In [4]:
#can convert  -#s to 0 if desired. I did not.

In [5]:
pop = pd.DataFrame(l)
pop.head()

0         1         2         3         4
0  5.059375  0.961295  1.711524  5.144468  4.170874
1  6.267895  5.628449  1.964724  0.931951 -0.436307
2  0.504200  5.216470  2.197606  3.679368  4.953164
3  2.906971  1.348998  3.622383  2.035576  3.496130
4  3.365182  6.058077 -0.677865  0.337954  3.255283

In [6]:
%timeit pop.apply(lambda hungry: hungry.sum()<17, axis =1).mean() #72% chance you will get a poptart
#python sum cuz it's in lambda

179 ms ± 1.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
#method 2

In [8]:
%timeit pop.apply(lambda hungry: hungry.values.sum()<17, axis =1).mean() 
#72% chance you will get a poptart
#uses numpy sum??? or
#python sum

28.9 ms ± 277 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
#method 3 fastest

In [10]:
%timeit (pop.sum(axis=1) < 17).mean() #72%  and uses pandas sum no python middle man

276 µs ± 1.29 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [11]:
(pop.sum(axis=1) < 17).mean()

0.7263

# Class

In [183]:
pop1= np.random.normal(loc = 3, scale = 1.5, size = (10_000, 5))

In [184]:
(pop1.sum(axis=1) < 17).mean()

0.7204

## 5 

Compare Heights

    Men have an average height of 178 cm and standard deviation of 8cm.
    Women have a mean of 170, sd = 6cm.
    Since you have means and standard deviations, you can use np.random.normal to generate observations.
    If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?



### Failed Work, scroll down

In [23]:
m = np.random.normal(178, 8, (10_000))
m = pd.DataFrame(m)
m.head(1)

0
0  168.1976

In [24]:
f = np.random.normal(170, 6, (10_000))
f = pd.DataFrame(f)
f.head(1)

0
0  171.145312

In [25]:
height = f.join(m, how = 'outer', lsuffix='_female', rsuffix='_male')
height.head(3)

0_female      0_male
0  171.145312  168.197600
1  170.641922  166.565772
2  163.407887  193.134451

In [26]:
height.iloc[:,1]

In [27]:
height.iloc[:,0] > height.iloc[:,1]

In [28]:
#height.apply(lambda arg: (arg.iloc[:,0]) > (arg.iloc[:,1])).mean()
#Too many indexes
#idk how to fix this

In [29]:
#try keeping it as an array below:

# Keeping as an array for #5, success

In [30]:
ma = np.random.normal(178, 8, (10_000))
fa = np.random.normal(170, 6, (10_000))
(fa>ma).mean()

0.2124

In [31]:
#21% chance

# Class

In [192]:
ma_c = np.random.normal(178, 8, (10_000))
fa_c = np.random.normal(170, 6, (10_000))

In [194]:
(fa_c > ma_c).mean()

0.2128

# 6 
When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100? 150? 450?

In [111]:
fails = (1/250)

In [120]:
n_stud = [[50], [100], [150], [450]]

In [124]:
np.multiply(fails, n_stud)

array([[0.2],
       [0.4],
       [0.6],
       [1.8]])

# Class

In [199]:
#0 = no issue 1 = issue
install_50 = np.random.choice([0,1], size = (10_000, 50), p = [249/250, 1/250])

In [200]:
(install_50.sum(axis=1) == 0).mean()

0.8188

In [202]:
install_100 = np.random.choice([0,1], size = (10_000, 100), p = [249/250, 1/250])
(install_100.sum(axis=1) == 0).mean()

0.6698

In [205]:
#150 students. Prob of install issue
install_150 = np.random.choice([0,1], size = (10_000, 150), p = [249/250, 1/250])
(install_150.sum(axis=1) > 0).mean()

0.4505

In [204]:
#prob of no issues when we have 450 students
install_450 = np.random.choice([0,1], size = (10_000, 450), p = [249/250, 1/250])
(install_450.sum(axis=1) == 0).mean()

0.1657

# 7
There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?
How likely is it that a food truck will show up sometime this week?

In [211]:
# 0 = no truck
trucks3 = np.random.choice([0, 1], (10000, 3), p = [.3, .7])

In [212]:
(trucks3.sum(axis=1)==0).mean()

0.0272

In [213]:
trucks7 = np.random.choice([0, 1], (10000, 7), p = [.3, .7])

In [214]:
(trucks7.sum(axis=1)==0).mean()

0.0004

In [215]:
#How unlikely is this? How likely is it that a food truck will show up sometime this week?
trucks2 = np.random.choice([0, 1], (10000, 2), p = [.3, .7])

In [217]:
(trucks2.sum(axis=1)>0).mean()

0.9112

# 8 
If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [218]:
bdays = np.random.randint(1, 365, size = (1_000_000, 23))

In [219]:
bday = pd.DataFrame(bdays)

In [220]:
#using lambda

In [221]:
bday.apply(lambda arg: len(arg) == len(set(arg)), axis =1).mean() 
# 49% they are all unique,  51% at least 2 people share a birthday

0.491667

In [232]:
bdays20 = np.random.randint(1, 365, size = (1_000_000, 20))
bday20 = pd.DataFrame(bdays20)

In [233]:
bday20.apply(lambda arg: len(arg) == len(set(arg)), axis =1).mean() #58% chance they are all unique

0.587616

In [234]:
bdays40 = np.random.randint(1, 365, size = (1_000_000, 40))
bday40 = pd.DataFrame(bdays40)

In [235]:
bday40.apply(lambda arg: len(arg) == len(set(arg)), axis =1).mean()  #10% chance they are all unique

0.107963

# Class

In [224]:
bd = np.random.choice(range(1,365), size = (10000,23))
bd

array([[282,  69, 176, ..., 134, 113,  72],
       [ 55, 300, 351, ..., 329,  35, 107],
       [234, 347, 254, ..., 240, 269,  38],
       ...,
       [246,  61, 192, ...,  71, 175, 131],
       [162, 306, 250, ..., 171, 355, 248],
       [120, 307, 315, ..., 180, 266, 145]])

In [225]:
(pd.DataFrame(bd).nunique(axis = 1) < 23).mean() # 50% at least 2 people share a birthday

0.5012

In [227]:
(pd.DataFrame(bd).nunique(axis = 1) == 22).mean() #exactly 2

0.363

In [ ]:
#examples for me

In [ ]:
# df[(df > 3).sum(axis=1) >= 3]

In [ ]:
# (pd.DataFrame(rolls).apply(lambda row: 3 in row.values, axis=1).mean())